### PR TITLE
Help users implement the ForwardDiff overload

### PR DESCRIPTION
**Pull request by antoine-levitt**

### CODE REVIEW

**Comment by maltezfaria** [comment]
Thanks. Let me add some docs explaining how to implement the interface, and we can iterate on this!

**Comment by maltezfaria** [comment]
I have rewritten the docs (see [here](https://maltezfaria.github.io/ImplicitIntegration.jl/dev/)). Perhaps we could add a concrete example on how to implement the interface for a custom type?

**Comment by antoine-levitt** [comment]
Let's just move this PR to the docs instead of the docstring?

**Comment by maltezfaria** [comment]
Yes, let's do that. We could have a small section showing how to implement the entire interface for a custom type. I suspect that could be useful, since as we have seen the simple bounds by interval arithmetic seem to become impractical when the function starts to get complicated (e.g. determinants, eigenvalues, etc).

**Comment by antoine-levitt** [comment]
Done

**Review by maltezfaria — APPROVED** [review]

**Pull request merged**
